package com.hedera.hashgraph.file.model;

// NOTE: This is a public API package and should be exported from the module. These classes are
// autogenerated from the protobuf, so they actually reside in a library on the classpath, but
// do need to be re-exported by the module. Thus, they do *NOT* live in a "proto" package because
// they are not inherently protobuf based (although the schema that defined them and the tool
// that generated them were protobuf based).
public record FileCreateTransactionBody(byte[] contents, String memo) {
}
